### ISSUE TITLE
Cut releases with features since the last release

### ISSUE THREAD

**Issue by alexlafroscia** [simplabs/qunit-console-grouper#46]
Hey! I'd really like to take advantage of the ability to disable the plugin in CI. Could you cut a release to NPM that includes the features that have landed recently? 

Thanks!

**Comment by Turbo87** [comment]
it's already released as v0.2.0, but it does look like I forgot to push the tag to the repo 🙈

**Comment by Turbo87** [comment]
fixed: https://github.com/simplabs/qunit-console-grouper/releases/tag/v0.2.0

**Comment by alexlafroscia** [comment]
Hmm... intersting. From what I can tell, setting `QUNIT_CONSOLE_GROUPER=false` does not actually disable the add-on, and I thought the issue was that that feature was not published. I see that's not the case, though...

**Comment by Turbo87** [comment]
> Now that I think of it, though, I the issue is that I'm pre-building the `dist` to test against and don't have it disabled then!

yeah, that sounds like an explanation 😅
