### ISSUE TITLE
Is there a way to optionally disable?

### ISSUE THREAD

**Issue by NullVoxPopuli** [simplabs/qunit-console-grouper#9]
I'd like to turn this off in C.I. / whenever I run in the terminal.

Maybe there is a way to only print if there is log output? idk

My main issue is that my CI logs are noisy now.

**Comment by Turbo87** [comment]
yeah, I noticed today that more recent versions of testem are showing these groupings too. I think it should be possible to disable it automatically in CI scenarios. I'll have a look at it next week.
